import theme from '../../theme';

export default {
    commonStyle: {
        flex: 1,
        width: '100%',
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        borderBottomWidth: 0.5,
        borderBottomColor: 'rgba(139,139,139,0.3)',
    },
    reviewLabel: {
        flex: 1,
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        height: 50,
        paddingHorizontal: 10,
        borderBottomWidth: 0.5,
        borderBottomColor: 'rgba(139,139,139,0.3)',
    },
    reviewUserList: {
        flex: -1,
        width: '100%',
        height: 200,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'stretch',
        borderBottomWidth: 0.5,
        borderBottomColor: 'rgba(139,139,139,0.3)',
    },
    reviewUserListNoData: {
        height: 200,
        width: '100%',
        flex: -1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    reviewUserListOption: {
        flex: -1,
        height: 40,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
    },
    selectOptionsTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.theme,
        textAlign: 'center',
        paddingVertical: 10,
        borderBottomColor: theme.theme,
        borderBottomWidth: 1,
        marginHorizontal: 15,
    },
    selectOptionsText: {
        fontSize: 15,
        paddingVertical: 5,
        textAlign: 'center',
    },
    appraiseStar: {
        padding: 10,
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
};
