import theme from '../../theme/index';

export default {
    container: {
        paddingVertical: 5,
        backgroundColor: theme.background,
    },
    contentOption: {
        backgroundColor: '#fff',
        paddingVertical: 5,
        height: 50,
        flex: -1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 5,
        paddingHorizontal: 10,
    },
    contentLabel: {
        flex: 3,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    contentInput: {
        flex: 7,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'stretch',
    },
    contentSelect: {
        flex: 7,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    selectTextLayout: {
        flex: 9,
        flexDirection: 'row',
        justifyContent: 'flex-start',
    },
    selectIconLayout: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    selectText: {
        color: '#000',
        fontSize: 15,
        paddingHorizontal: 5,
    },
    selectOptionsTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.theme,
        textAlign: 'center',
        paddingVertical: 10,
        borderBottomColor: theme.theme,
        borderBottomWidth: 1,
        marginHorizontal: 15,
    },
    selectOptionsText: {
        fontSize: 15,
        paddingVertical: 5,
        textAlign: 'center',
    },
    contentOptionBig: {
        backgroundColor: '#fff',
        paddingVertical: 5,
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 5,
        paddingHorizontal: 10,
    },
    contentOptionBigLabel: {
        alignSelf: 'stretch',
        height: 40,
        flex: -1,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    contentOptionBigInput: {
        alignSelf: 'stretch',
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'stretch',
    },
    imageListLayout: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        alignItems: 'stretch',
        paddingVertical: 10,
    },
    imageLayout: {
        width: 85,
        height: 85,
        flex: -1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageDelBtn: {
        position: 'absolute',
        right: -10,
        top: -10,
        borderRadius: 10,
        width: 20,
        height: 20,
        zIndex: 99,
        backgroundColor: '#fff',
    },
    image: {
        width: 70,
        height: 70,
    },
};
